---
sudo: false
language: ruby
rvm:
  - 2.5
  - 2.6
  - 2.7
gemfile:
  - gemfiles/rails_4_2.gemfile
  - gemfiles/rails_5_0.gemfile
  - gemfiles/rails_5_1.gemfile
  - gemfiles/rails_5_2.gemfile
  - gemfiles/rails_6_0.gemfile
before_install:
  # uninstall bundler 2.0 and greater for rails 4.2 testing
  # and make sure its not the default gem
  - "find /home/travis/.rvm/rubies -wholename '*default/bundler-*.gemspec' -delete"
  - gem install bundler -v '< 2'
script:
  - bundle exec rspec
